### ISSUE TITLE
关于套接字编程的一个问题

### ISSUE THREAD

**Issue by shinytang6** [moranzcw/Computer-Networking-A-Top-Down-Approach-NOTES#1]
刚开始阅读这本书
看到书本P107开始讲的套接字编程
我照着书本上打了一遍代码，测试下来在本机（也就是ip 127.0.0.1）可以运行
但是我把UDPServer.py放到我的阿里云服务器（并将hostname改为服务器公网ip）上运行，UDPClient就没反应了?请问您有遇到类似问题吗？

**Comment by moranzcw** [comment]
谢谢关注。
我自己使用VPS测试时是没有问题的。可能室是由于阿里云主机默认不开放所有端口导致的，您可以试试把需要的端口打开。

2017-10-16 19:50 GMT+08:00 Mr.tang <notifications@github.com>:

**Comment by shinytang6** [comment]
谢谢，问题已经解决。
期待您有机会能将这个repo继续做下去。
