### ISSUE TITLE
wireshark lab IP 部分 第7题

### ISSUE THREAD

**Issue by ThoundsN** [moranzcw/Computer-Networking-A-Top-Down-Approach-NOTES#16]
显然应该分析network layer 的 identification number,  截图的却是 ICMP 部分的

**Comment by CHN-STUDENT** [comment]
抱歉，当时错误理解成这道题是问IP数据报中数据段里面的标识符，所以才会写成IP数据段里面是ICMP协议，标识字符不一样。

您说的很对，应该是IP数据报（IP datagram）的 identification number 标识符，我为我的粗心和学习的不严谨感到抱歉，同时也感谢您指出我的错误和帮助改正！

题目是问的这部分，在IP数据报中里面标识字符应该如何变化。
 
![image](https://user-images.githubusercontent.com/21209416/53727552-797bd880-3eab-11e9-9c61-3de468fc7f3f.png)

每次不一样，且递增增长。

![image](https://user-images.githubusercontent.com/21209416/53727680-bfd13780-3eab-11e9-9602-d4bea85ef63b.png)
![image](https://user-images.githubusercontent.com/21209416/53727711-d1b2da80-3eab-11e9-8118-bdd4cb47f300.png)

再次感谢您！

**Comment by CHN-STUDENT** [comment]
如果您发现有其他题我有做错和不足的地方。欢迎您和其他人继续指出！
不胜感激！
