### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by fatmanhappycode** [moranzcw/Computer-Networking-A-Top-Down-Approach-NOTES#17]
计算机网络实验-HTTP1.pdf里面第5题的时间是格林威治时间 (GMT)，能不能稍微提及一下，初学者有可能以为是北京时间，然后以为自己弄错了

**Comment by CHN-STUDENT** [comment]
嗯，GMT确实是格林威治时间，GMT+8才是北京时间...不过我当时做实验没有看到这点啊...
