### ISSUE TITLE
Wireshark实验：HTTP实验五一个输入小错误

### ISSUE THREAD

**Issue by promethuesYuan** [moranzcw/Computer-Networking-A-Top-Down-Approach-NOTES#18]
在Wireshark实验：HTTP实验五中文翻译中，实验让我们访问一个需要账号登录的网站。这个任务下最开始描述给了一个URL，在具体步骤中也给了一个URL，但是后面一个URL在最后一部分少了一个“-”，即正确的应该是HTTP-wireshark-file5.html，而后面的漏打后为HTTP-wiresharkfile5.html，会导致登录后看到的界面是404 Not Found, 而不是正确结果，期望可以修改一下。

**Comment by CHN-STUDENT** [comment]
嗯，当时做实验都是用的word然后导出pdf，所以有些地址会有排版错误....我应该改成markdown的
