### ISSUE TITLE
4.17, Wireshark Lab2 

### ISSUE THREAD

**Issue by DesperateL** [moranzcw/Computer-Networking-A-Top-Down-Approach-NOTES#20]
I think two images were downloaded in parallel. Because of their waterfall almost overlaps each other.
![image](https://user-images.githubusercontent.com/25661962/64917812-376f1000-d7c7-11e9-8c23-75e3eba7acbe.png)

**Comment by CHN-STUDENT** [comment]
Thanks for your issue. 
I am looking at the offical answer.It also says two images were downloaded in parallel. 
In my experiment, i thought two image were starting to download in different time.
The author and you thought the time different can miss.
The experiment does not have correct answer. But we can find others views in talking.
Thank you!

感谢您的疑问，我查阅了官方答案，官方也说明这两张图片是同时下载的。
在我当时实验中，我认为两张图片下载get请求有时间差，所以我说有差别。
我猜测您和作者都觉得这个时间很小可以忽略不记，
这实验没有绝对的答案对错，只愿我们在交流过程中能够发现其他人的想法和找出自己的不足。
再次感谢您！

**Comment by DesperateL** [comment]
thank you～
